{
    'name':"Office Management",
    "description":"Office Management Module using other modules",
    'version':'1.0',
    'category':"management",
    'summary':"No summary required",
    'installable':True,
    'autoinstall':True,
    'application':True,
    'author':'Jatin',
    'depends':['hr','product','account'],
    'data':['security/ir.model.access.csv',
            'views/employee.xml',
            'views/department.xml',
            'views/payment.xml',
            'views/attendance.xml',
            'views/event.xml',
            'views/pop.xml',
            'views/pop2.xml',
            'views/referal.xml',
            'views/inventory.xml',
            'views/menus.xml', 
            ],
}